docker-build:
	docker build -t advancedtelematic/dhall-json .

docker-push:
	docker push advancedtelematic/dhall-json

docker-run:
	docker run -it --rm -v ${CURDIR}:/data advancedtelematic/dhall-json bash
