source 'https://rubygems.org'

gem 'asciidoctor', '>= 1.5.5'
gem 'pygments.rb'
gem 'asciidoctor-pdf', '>= 1.5.0.alpha.15'
gem 'asciidoctor-diagram'
gem 'prawn-gmagick', '>= 0.0.9'
gem 'asciidoctor-latex', '>= 1.5.0.17.dev'
